version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    image: komeetta/inventory-management-system:latest_v1
    container_name: inventory-app
    depends_on:
      - db
    environment:
      JDBC_URL: "jdbc:mariadb://db:3306/inventory_db"
      JDBC_USER: "app_user"
      JDBC_PASSWORD: "1234"
      DB_MODE: "reset"
    ports:
      - "8081:8080" # Change the port if needed

volumes:
  mariadb_data:
